Add SO-16.
pointhi/kicad-footprint-generator pull request #521
Opened 2020-04-04 13:22 UTC by jmgao

Datasheet: https://www.nxp.com/docs/en/package-information/SOT109-1.pdf
Screenshot:
![so-16](https://user-images.githubusercontent.com/593995/78451816-99e10e00-763c-11ea-9da3-0f6b6431ddb4.png)

2020-08-23 20:02 UTC, chschlue requested changes
See line comments.
Also, please add 1.75mm `overall_height`

2020-09-08 03:00 UTC, jmgao commented on scripts/Packages/Package_Gullwing__QFP_SOIC_SO/size_definitions/so.yaml
> +    maximum: 10.0
Done.

2020-09-08 03:00 UTC, jmgao commented on scripts/Packages/Package_Gullwing__QFP_SOIC_SO/size_definitions/so.yaml
> +    maximum: 4.0
Done.

2020-09-08 03:05 UTC, chschlue approved these changes
Thanks

2020-09-08 03:05 UTC, merged