add hsop-8 2.3x2.3mm ep
pointhi/kicad-footprint-generator pull request #533
Opened 2020-04-20 19:09 UTC by matthuszagh

Adds a 2.3x2.3mm EP HSOP-8 version for [L7980](https://www.st.com/resource/en/datasheet/l7980.pdf).

2020-08-23 18:36 UTC, chschlue requested changes

2020-08-23 18:36 UTC, chschlue commented on scripts/Packages/Package_Gullwing__QFP_SOIC_SO/size_definitions/hsop.yaml
> +    tolerance: 0.1
No explicit nominal dimension given, please use min/max notation.

2020-08-23 18:36 UTC, chschlue commented on scripts/Packages/Package_Gullwing__QFP_SOIC_SO/size_definitions/hsop.yaml
> +    tolerance: 0.15
Wrong dimensions. Also, see above.

2020-08-23 18:36 UTC, chschlue commented on scripts/Packages/Package_Gullwing__QFP_SOIC_SO/size_definitions/hsop.yaml
> +    tolerance: 0.1
No EP tolerance given.

2020-08-28 16:04 UTC, matthuszagh commented
Thanks for the review @chschlue! I've implemented your changes. Let me know if any issues.

2020-08-30 08:24 UTC, chschlue approved these changes
Thanks.

2020-08-30 08:24 UTC, merged