Add HVQFN-40
pointhi/kicad-footprint-generator pull request #559
Opened 2020-05-28 09:32 UTC by jneiva08

Created footprint for HVQFN 40

Datasheet: https://www.nxp.com/docs/en/package-information/SOT618-1.pdf
and https://www.nxp.com/docs/en/nxp/data-sheets/PN532_C1.pdf

2020-08-23 21:24 UTC, cpresser requested changes

2020-08-23 21:24 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/hvqfn.yaml
> +    maximum: 0.5
nominal: 0.4

2020-08-23 21:24 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/hvqfn.yaml
> +    maximum: 0.3
nominal: 0.21

2020-08-23 21:24 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/hvqfn.yaml
> +HVQFN-40-1EP_6x6mm_P0.5mm_EP4.25x4.25mm:
The nominal EP_size is 4.1 which is also in the output of the generator.

2020-08-23 21:24 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/hvqfn.yaml
> +  #EP_size_limit_y: 2.7  #for relatively large EP pads (increase clearance)
The recommended footprint has way less paste than the generated pads:
![image](https://user-images.githubusercontent.com/17516572/90989014-9cb2b000-e597-11ea-81b4-9cb97f181043.png)
![image](https://user-images.githubusercontent.com/17516572/90989028-beac3280-e597-11ea-8825-3bc9da2727a8.png)

TBH, I am not sure what to do here. @poeschlr can you help?

2020-08-23 21:52 UTC, jneiva08 commented
@cpresser have made the modifications you requested, except the last one
I don't know too. let me know what should change.

2020-09-17 19:32 UTC, cpresser commented
I played around a little with the parameters. To get the paste-pads exactly the size of the datasheet one has to enter `19.2742%` (calculated by 9*0.6^2/4.1^2).
Getting the paste pads onto the correct position only works with the thermal_vias variant when `grid: [0.9, 0.9]` is used.

**But that is all useless.** This is supposed to be an IPC compliant footprint. Not a vendor specific one. It took me a while to come to that obvious conclusion.
Thus, you can just have the default values for pad geometry.

I just have one more wish, please remove the commented lines. They always look like they are there for a reason.  But they are not which is bamboozling. Its just copy-paste leftovers. While you are at it, also remove them for the other two parts in that file.

2020-09-22 17:52 UTC, myfreescalewebpage commented
@jneiva08 ping, can you follow the query of @cpresser (removing comment lines in the yaml file)

2020-09-22 18:23 UTC, jneiva08 commented
@myfreescalewebpage @cpresser 
When you mean remove comment lines you mean:
`#manufacturer
#part_number
#ipc_density
#EP_paste_coverage
#EP_size_limit_x
#EP_size_limit_y
#min_annular_ring
#EP_num_paste_pads
#grid
#bottom_pad_size
#paste_avoid_via
#chamfer_edge_pins
#pin_count_grid
#pad_length_addition
#suffix
#include_suffix_in_3dpath`

2020-09-22 18:31 UTC, myfreescalewebpage commented
@jneiva08 yes

2020-09-22 20:00 UTC, jneiva08 commented
@myfreescalewebpage @cpresser, have made the changes have requested, hope didn't break the file. Need to make more changes?

2020-09-22 20:56 UTC, cpresser commented
Thanks, that looks great.
The merge-commit was not needed, but its not a problem either. I am going to squash this branch before merging it to master anyway.

Can you please update the footprint PR (https://github.com/KiCad/kicad-footprints/pull/2303) with the latest generator output (just the HVQFN-40) file. Then I will merge that as well.

2020-09-22 20:56 UTC, cpresser approved these changes

2020-09-22 20:57 UTC, merged

2020-09-22 21:03 UTC, jneiva08 commented
Thanks for your time, I will soon update in kicad-footprints