Add DFN-8 for Linear LTC2451
pointhi/kicad-footprint-generator pull request #569
Opened 2020-06-08 10:27 UTC by yankee14

Add 8-pin DFN with 1 EP from Linear LTC2451

Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/2451fg.pdf#page=17

kicad-symbols: PLACEHOLDER
kicad-footprints: PLACEHOLDER
kicad-footprint-generator: PLACEHOLDER

Screencap:

![DFN-8-1EP_2x3mm_P0 5mm_EP0 56x2](https://user-images.githubusercontent.com/12487802/84020610-b35a4b00-a948-11ea-98b6-13ae3eba23ec.png)

2020-06-08 10:31 UTC, yankee14 commented
Ignore git branch name, I misread the datasheet when I branched.

2020-06-25 09:07 UTC, yankee14 commented
The silkscreen line is confusing, it suggests pin 1 is on the top right. But the assembly layer shows it correctly.

2020-08-30 08:16 UTC, chschlue requested changes

2020-08-30 08:16 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    tolerance: 0
0.1

2020-08-30 08:16 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    tolerance: 0
0.1

2020-08-30 08:16 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    maximum: 0.8
Please use nominal and tolerance, as given in the datasheet.

2020-08-30 08:16 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    maximum: 0.3
See above

2020-08-30 08:16 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    maximum: 0.5
See above

2020-08-30 08:16 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    maximum: 0.61
See above

2020-08-30 08:16 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    maximum: 2.2
See above

2020-08-31 01:54 UTC, yankee14 commented
Hmm I have never seen this change request feature before. Is it like applying patch files? This is cool.

2020-08-31 01:58 UTC, yankee14 commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    tolerance: 0
What do you mean by 0.1? The tolerance?

2020-08-31 02:05 UTC, yankee14 commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    tolerance: 0
Yes you must mean that :)

2020-08-31 06:48 UTC, chschlue approved these changes
Thanks.

It's GH's review feature (available on the `Files changed` tab). I like it because it clearly separates concrete change requests from chit-chat.

2020-08-31 06:49 UTC, merged