Add S-PWQFN-N16 with 1.7x1.7 EP
pointhi/kicad-footprint-generator pull request #590
Opened 2020-08-25 21:29 UTC by zonque

2020-08-29 10:00 UTC, zonque commented
Could I get a review on this one? I have a symbol pending that depends on this footprint.

2020-08-29 13:10 UTC, chschlue commented
Of course! Sooner or later. Probably later.

There are 122 open PRs and yours is four (!) days old.
Also, you couldn't even be bothered to reference those pending PRs.

Hint: Not creating additional work for reviewers is among the best ways to get a review in time.

2020-08-29 13:34 UTC, zonque commented
Oh, my apologies. I wasn't aware of the backlog, and I didn't mean to be pushy. The symbol is not pending as a PR yet. Will post as soon as the footprint is merged. Take your time, thanks for your work, and sorry again!

2020-08-29 14:25 UTC, chschlue commented
That's not how it works.
Please open all related PRs cross-reference them.

2020-09-19 20:57 UTC, chschlue requested changes
There is nothing special about this QFN footprint.
Please use its default name of `WQFN-16-1EP_3x3mm_EP1.7x1.7mm` and move the size definition to https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/wqfn.yaml

2020-09-19 20:57 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/qfn_texas.yaml
> +    tolerance: 0.1
Please use the package pad dimensions of 1.66mm for `EP_size_[xy]` and add `EP_size_[xy]_overwrite: 1.7` to get the suggested EP land size.

2020-09-19 20:57 UTC, chschlue commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/qfn_texas.yaml
> +    EP_paste_coverage: 0.5
Please remove to use script defaults.

2020-09-27 17:26 UTC, zonque commented
Thanks for the feedback. While adding moving it to the other location, I realized there is a definition already that serves the need quite well. Don't know why I didn't see that before. Sorry for the noise, I'll just go for the already existing option then.

2020-09-27 17:26 UTC, closed without merging