Add WDFN-8 1EP 2x2mm EP0.8x1.2mm
pointhi/kicad-footprint-generator pull request #612
Opened 2020-09-07 23:46 UTC by yankee14

`kicad-symbols`: https://github.com/KiCad/kicad-symbols/pull/2783

Datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/20005474E.pdf#page=25

EP chamfer not working...

![WDFN-8-1EP_2x2mm_P0 5mm_EP0 8x1](https://user-images.githubusercontent.com/12487802/92420669-600bba80-f13a-11ea-9024-4e72bc793bea.png)

2020-09-11 20:51 UTC, cpresser requested changes

2020-09-11 20:51 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +  lead_len_max: 0.35
This style is deprecated.
Please use:
```
lead_width: 0.2 ..0.25 ..0.3
lead_len: 0.25 ..0.3 .. 0.35
```

Or

```
lead_width: 0.25 +/- 0.05
lead_len: 0.3 +/- 0.05
```

see https://github.com/pointhi/kicad-footprint-generator/blob/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/Readme.md

2020-09-11 20:51 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +    tolerance: 0
Please write it like
```yaml
body_size_x: 2.0
body_size_y: 2.0
```

2020-09-11 20:51 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +  #include_suffix_in_3dpath: 'False'
Please remove the unused lines. They just add noise. Same with the commented lines above.

2020-09-11 20:51 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/dfn.yaml
> +  chamfer_edge_pins: 0.25
This is supposed to be used with QFNs. Not for the exposed pad.
Currently the generator does not support a chamfered EP.

2020-09-13 15:10 UTC, chschlue commented
@cpresser assigned you because you already reviewed it.

2020-09-13 17:57 UTC, cpresser approved these changes

2020-09-13 17:57 UTC, merged