Add UFQFPN-32-1EP_5x5mm_P0.5mm_EP3.5x3.5mm.
pointhi/kicad-footprint-generator pull request #621
Opened 2020-09-10 18:32 UTC by piotr-wiszowaty

2020-09-10 18:42 UTC, cpresser requested changes

2020-09-10 18:42 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/ufqfpn.yaml
> +  ipc_class: 'ufqfpn' # 'qfn_pull_back'
That is wrong. It is either `qfn_pull_back` or not set all all.
Please remove that line.

2020-09-10 18:42 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/ufqfpn.yaml
> +  #include_suffix_in_3dpath: 'False'
You can remove `chamfer_edge_pins`. The recommended layout only has this on Pin1.

Please also remove the unused lines here and above.

2020-09-10 18:42 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/ufqfpn.yaml
> +    nominal: 5
There is tolerance for that in the datatsheet. Please add that
```yaml
body_size_x: 5 +/-0.1
body_size_y: 5 +/-0.1
```

2020-09-10 18:42 UTC, cpresser commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/ufqfpn.yaml
> +    EP_paste_coverage: 0.75
I don't see a recommendation for paste coverage in the datatsheet. Did I miss it?
If no, remove that line, then the value defaults to 0.65 which is recommended by IPC.

2020-09-11 19:52 UTC, cpresser commented
One more thing: can you please remove the  commented out lines. They just add noise. Further contributors will just copy them and add more noise. IMHO this is cargo cult and should stop.

2020-09-11 19:56 UTC, piotr-wiszowaty commented
Sure. Done.

On 9/11/20 9:53 PM, cpresser wrote:
>
> One more thing: can you please remove the commented out lines. They 
> just add noise. Further contributors will just copy them and add more 
> noise. IMHO this is cargo cult and should stop.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/pointhi/kicad-footprint-generator/pull/621#issuecomment-691283804>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/ABIAOEAOVU7H6W3EDRG6IPDSFJ52XANCNFSM4RFTJVKA>.
>

2020-09-11 21:05 UTC, cpresser commented
Thanks!

2020-09-11 21:05 UTC, cpresser approved these changes

2020-09-11 21:05 UTC, merged