QFN-12 footprint for MMZ09332B
pointhi/kicad-footprint-generator pull request #640
Opened 2020-09-24 15:43 UTC by drid

https://www.nxp.com/docs/en/data-sheet/MMZ09332B.pdf

One issue regarding EP. Mechanical has dimensions 1.4mm-1.6mm which result in 1.5mm EP but recommended land pattern has 1.6mm EP
![image](https://user-images.githubusercontent.com/1120609/94167791-9618a080-fe95-11ea-860e-3431276e545f.png)
![image](https://user-images.githubusercontent.com/1120609/94167833-a29cf900-fe95-11ea-82f5-fb1df16a7bb4.png)

How is this resolved in the generator?
Also is there a way to create a 3-2-3 thermal via pattern?

2020-09-24 15:49 UTC, chschlue commented
The desired EP size is set using `EP_size_[xy]_overwrite` (see https://github.com/pointhi/kicad-footprint-generator/tree/master/scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON#exposed-pad-handling).
The via pattern is not possible at this time.

2020-09-24 17:44 UTC, myfreescalewebpage commented
@drid thanks

 -[ ] lead_width minimum value should be 0.18
- [ ] You should remove all the comment lines

Else @chschlue @poeschlr it seems ok for me but because it's a bit specific I prefer you have a second look

Joel

2020-09-24 19:00 UTC, chschlue requested changes
Added line comments.

Anything specific you were asking about, @myfreescalewebpage?

2020-09-24 19:08 UTC, myfreescalewebpage commented
@chschlue the footprint name and EP eventually but if my understanding is correct, this is the best we can do to have something closed to the datasheet definition, isn't it ?

2020-09-24 19:17 UTC, chschlue commented
Ah. Wasn't paying attention to the name.
Footprint doesn't look very special to me, unless I'm missing something `NXP_` isn't necessary and the size def can be moved to `qfn-1x.yaml`.

2020-09-25 10:56 UTC, drid commented on scripts/Packages/Package_NoLead__DFN_QFN_LGA_SON/size_definitions/qfn/special_qfn.yaml
> +    maximum: 3.1
I misinterpreted a 0.1mm dimension. Changing to nominal only

2020-09-26 09:49 UTC, chschlue approved these changes
Thanks.

2020-09-26 09:49 UTC, merged